const data = {
    products:[
        {
            _id:'1',
            name:'Green Capsicum',
            Category:'Vegetables',
            image:'/images/capsicum.jpg',
            price:60,
            brand:'JK Traders',
            rating:4.5,
            numReviews: 10,
            description:'Fresh Green Capsicum',
        },
        {
            _id:'2',
            name:'Brocolli',
            Category:'Vegetables',
            image:'/images/brocolli.jpg',
            price:120,
            brand:'JK Traders',
            rating:4.0,
            numReviews: 10,
            description:'Fresh Green brocolli',
        },
        {
            _id:'3',
            name:'Green Pea',
            Category:'Vegetables',
            image:'/images/greenPea.jpg',
            price:50,
            brand:'JK Traders',
            rating:4.0,
            numReviews: 10,
            description:'Fresh Green Peas',
        },
        {
            _id:'4',
            name:'Tomato',
            Category:'Vegetables',
            image:'/images/tomato.jpg',
            price:60,
            brand:'JK Traders',
            rating:4.0,
            numReviews: 10,
            description:'Tomato',
        },
        {
            _id:'5',
            name:'Lady Fingre',
            Category:'Vegetables',
            image:'/images/Bhindi.jpg',
            price:70,
            brand:'JK Traders',
            rating:4.0,
            numReviews: 10,
            description:'Bhindi',
        },
        {
            _id:'6',
            name:'Onion',
            Category:'Vegetables',
            image:'/images/onion.jpg',
            price:70,
            brand:'JK Traders',
            rating:.05,
            numReviews: 10,
            description:'Onion',
        },
        {
            _id:'7',
            name:'Potato',
            Category:'Vegetables',
            image:'/images/potato.jpg',
            price:60,
            brand:'JK Traders',
            rating:4.5,
            numReviews: 10,
            description:'Potato',
        },
        {
            _id:'8',
            name:'Coriander',
            Category:'Vegetables',
            image:'/images/coriander.jpg',
            price:40,
            brand:'JK Traders',
            rating:5.0,
            numReviews: 10,
            description:'Coriander',
        },
    ]
}


export default data;